language: php
php:
  - 5.6

matrix:
  allow_failures:
    - php: 5.6
install:
  - curl -s http://getcomposer.org/installer | php
  - php composer.phar install --dev --no-interaction

script:
  - php wh_application/vendor/bin/phpunit -c wh_application/tools/validation/PhpUnit.xml

after_success:
  - php wh_application/vendor/bin/coveralls -v