language: php
php:
  - 5.6

matrix:
  allow_failures:
    - php: 5.6

script:
  - php wh_application/vendor/bin/phpunit -c wh_application/tools/validation/PhpUnit.xml

after_success:
  - travis_retry php wh_application/vendor/bin/coveralls -v